on:
  push:
    tags:
    - '*'

jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./build.sh
      - run: |
          tar -czvf install.tar.gz install
          tar -czvf libtdjson.xcframework.tar.gz libtdjson.xcframework
      # CocoaPods will extract archive file and install `nothing` to pod if the folder depth > 2 (bug?)
      # and it will also move single folder to root (no option to turn off, https://github.com/CocoaPods/CocoaPods/pull/728), so can't just archive ./dylibs
      - name: libtdjson.xcframework.tar.gz
        run: |
          tar -czvf libtdjson.xcframework.tar.gz LICENSE libtdjson.xcframework
      - name: cocoapod_modulemap.tar.gz
        run: |
          cd install/tdjson/iOS/include
          cp ../../../module.modulemap .
          tar -czvf cocoapod_modulemap.tar.gz module.modulemap td/telegram/td_json_client.h td/telegram/tdjson_export.h
          rm module.modulemap
          mv cocoapod_modulemap.tar.gz ../../..
          cd ../../..
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "install.tar.gz,libtdjson.xcframework.tar.gz,cocoapod.tar.gz,cocoapod_modulemap.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - `install.tar.gz`: Dev pack including everything for all platforms
            - `libtdjson.xcframework.tar.gz`: Dynamic libraries for all platforms
            - `cocoapod.tar.gz`: Files for CocoaPods, see ./libtdjson.podspec
            - `cocoapod_modulemap.tar.gz`: Example module files for CocoaPods
      - name: pod trunk push
        run: |
          pod trunk push --allow-warnings libtdjson.podspec
          pod trunk push --allow-warnings flutter_libtdjson.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{secrets.COCOAPODS_TRUNK_TOKEN}}
  notify:
    if: cancelled() == false
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ needs.build.result }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
