on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./build.sh
      - run: |
          tar -czvf install.tar.gz install
          tar -czvf libs.tar.gz libs
          tar -czvf dylibs.tar.gz dylibs
          # cocoapod will flatten single folder to root, and it will cause installing nothing in pod folder, prevent it by adding a empty folder
          mkdir .placeholder
          tar -czvf cocoapod.tar.gz dylibs/iOS/libtdjson.dylib dylibs/macOS/libtdjson.dylib LICENSE .placeholder
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "install.tar.gz,libs.tar.gz,dylibs.tar.gz,cocoapod.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - `install.tar.gz`: dev pack including everything for all platforms
            - `libs.tar.gz`: static lib files for all platforms
            - `dylibs.tar.gz`: dynamic lib files for all platforms
            - `cocoapod.tar.gz`: files for cocoapod, see ./libtdjson.podspec
      - run: |
          brew install coreutils
          dir=$(dirname $(grealpath $(which pod)))/../libexec/gems
          f=$(grep --include=\*.rb -rnwl $dir -e "unless lib_name.end_with?('.a')")
          sed -i '' "s/unless lib_name.end_with?('.a') && lib_name.start_with?('lib')/unless (lib_name.end_with?('.a') || lib_name.end_with?('.dylib')) \&\& File.basename(lib_name).start_with?('lib')/g" $f
          f=$(grep --include=\*.rb -rnwl $dir -e "validate_nonempty_patterns(attr_name, :error)")
          sed -i '' "s/validate_nonempty_patterns(attr_name, :error)/(attr_name.to_s == 'vendored_libraries') || validate_nonempty_patterns(attr_name, :error)/g" $f
          pod trunk push --allow-warnings libtdjson.podspec
          pod trunk push --allow-warnings flutter_libtdjson.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${secrets.COCOAPODS_TRUNK_TOKEN}
  notify:
    if: cancelled() == false
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ needs.build.result }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
